### PR TITLE
[Rewrite] Metadata support, supported features consistency, testing consistency

### PR DESCRIPTION
**Pull request by OJezu**
This PR is a rewrite of whole library, with changes to supported feature set, removing some methods (`getString`, `getStat`), adding support for metadata and headers, adding file listing, and using same test set for all storages.

I understand this PR might not be welcome, if there is no will to merge, I will fork. Or maybe some more features are needed, or some changes are too radical. Since 1.0.0 is not completely out yet, this might be a last call if this gets merged or not.

### add flatList method to all storages, listing files with given prefix
method is called `flatList` due to cloud providers allowing using separators, to have lists more akin normal filesystem listings, with directories etc. `flatList` just returns everything with name matching prefix, with no regard to directory structure, real or emulated.
### remove unique features from storages - append, prepend
Those were only implemented in `local` storage, making changing provider unfeasible. If they are to be reintroduced, they should not be defined in `Storage` class.
### add metadata and headers support to all storages - getProperties, and properties are returned along getBuffer
Support for headers, like contentType, and custom user-set metadata - metadata keys are limited to `camelCase` words, to allow same metadata keys to be used with all providers. For some providers, the names are mangled, or otherwise the letter case may be lost (for Azure they are converted to snake_case)
### remove getString - use getBuffer as safer alternative
getString is not binary safe. Just use `(await storage.getBuffer()).toString()`.
### remove getStat
getStat removed in favor of getProperties, returning all headers and metadata
### use single test suit to test all storages
Since tests were depending on multiple methods per test anyway, there is no point in having separate tests for all storages, as all storages should have exactly the same behaviour
### use jest instead of japa for testing
While `japa` is fast, it lacks many features, like filtering tests in command line, or even running specific test file in isolation.
### always test with real s3, remove docker tests
Uneeded complexity when running tests, either all of them should be in docker, or none. Also test against real s3, so tests are topical.
### consistent class/variable naming, storage is always storage
Storage was referred to as Storage sometimes, and Driver the other times.
### local: clean-up empty directories left, when files are deleted
Just a cosmetic measure, to keep empty directories away.
### local: store data in root/data/ directory and metadata in root/meta/ directory
This is a big one. Local driver needs either to ignore metadata, or store it somewhere. To make sure that stored metadata cannot be directly accessed via Storage, I separated the data and metadata directories, moving physical storage elsewhere. Data and metadata directories can also be set directly.
Alternative solutions are:
 - not supporting metadata in local storage
 - keeping the metadata in specially named files, like `${dirname}/.flydrive-metadata.${basename}` and either filtering direct access to those files, or not bothering to filter the access to those files. Former solution would make some very-specific file names not possible, the latter seems like a bad idea.
 - trying to use something like `xattr` - specific to underlying filesystem and OS, not sure about xattr support in Node.js
### manager: don't treat built-in and "extended" storage any different
There was simply no reason to do it
### manager: cache disks storage instances, and don't allow mutating existing disks
Caching storage instances saves some set-up time on each access to disk, disabling mutation of disks with second argument to `manager.disk()` was needed to make caching work. Instead, new disks can be added at any time with `manager.addDisk(name, config)`

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @OJezu! 👋 

Sorry for the delay!

I love many features of this PR, the only thing I don't like is how big it is.
Could you please try to create multiple PR with only one change at a time?

**Comment by OJezu** [comment]
Hi @RomainLanz I just returned from vacation, I will try to separate PR by issues as are described in sections here.

**Comment by OJezu** [comment]
@RomainLanz I've separated the change into 8 commits, would you like me to open a PR for each of them (they might be interdependent, so that might be a problem), or is a single PR with 8 commits OK?
https://github.com/gamfi/flydrive/commits/feature/api-cleanup-broken-up

The tests are fixed only in the last commit. I will go over them once tomorrow more to make sure at least they compile from TypeScript.

**Comment by RomainLanz** [comment]
Few changes have been merge through this PR https://github.com/Slynova-Org/flydrive/pull/133

Thanks for your contribution!

**Pull request closed without merging**
