### PR TITLE
add config param to disk method

### PR DESCRIPTION
**Pull request by molobala**
That will allow passing custom config object to Driver when calling `disk` method

### CODE REVIEW

**Comment by RomainLanz** [comment]
Could you please add some tests?

**Comment by molobala** [comment]
done! 

By the way, I think you must add package-lock to gitignore, since when we do a`npm i` , it changes probabaly.

**Comment by RomainLanz** [comment]
Thanks!

**Comment by fryck** [comment]
Hi, I need this feature but i can't find this in the last package release 1.0.3

**Pull request merged**
