### PR TITLE
Adds support for Aliyun OSS Storage Driver

### PR DESCRIPTION
**Pull request by borie88**
Requires ali-oss npm package: npm install oli-oss --save

### CODE REVIEW

**Comment by RomainLanz** [comment]
Wow, thank you @borie88! 
Could you add some tests to your PR?

**Comment by borie88** [comment]
Sure thing. Will do that ASAP

**Comment by RomainLanz** [comment]
Hey @borie88!

Any news on this?

**Comment by RomainLanz** [comment]
Hey @borie88! 👋 

Thanks for all those updates, could you please also add some tests to your proposal?

If you could use [this PR](https://github.com/Slynova-Org/node-flydrive/pull/54) to also implement your testing env in Docker that would be awesome!

**Comment by borie88** [comment]
Oops, forgot i was still updating the PR here as well. Have some refactoring to do to comform with the more recent dependency updates, and the Tencent cloud service still does not have support for getStream

**Comment by RomainLanz** [comment]
Hey @borie88! 👋 

I'm closing this for the moment since we are doing big refactoring for the next release (including TS rewrite).

You can still safely use your driver by extending the manager like you are doing now.
Feel free to re-open a PR with the needed change when the next release will be out. 🤗

**Comment by borie88** [comment]
Ok, does that mean I'll need to redo the extension in TS? Also, I highly recommend we figure out a good way to implement testing for this as it needs credentials and a bucket to work correctly. I would not recommend docker only if there is no generic solution

**Comment by adlanarifzr** [comment]
Hi @borie88 . May I know if this PR will be continued?

**Comment by borie88** [comment]
Hey @adlanarifzr . Yes, I actually have a typescript version ready in my fork. Will submit a pull request in the coming days once the automated testing gets figured out

**Pull request closed without merging**
