### PR TITLE
Adding read method

### PR DESCRIPTION
**Pull request by brenoos**
I just create a method read for return only the metadata without the entire object.

### CODE REVIEW

**Review by brenoos — COMMENTED** [review]
Dont want to merge this PR?

**Comment by RomainLanz** [comment]
Hey @brenoos! 👋 

Thanks for your time on this PR! 💙 

We were on the process to move to the 1.0 release which is a complete TS rewrite of the package.
Feel free to send this PR again with the new code which has been released.

**Comment by targos** [comment]
Note that with the new API, you can get this object with `(await drive.getStat(location)).raw)`

**Comment by brenoos** [comment]
Thanks for the reply

**Pull request closed without merging**
