### PR TITLE
Allow using dynamic config object 

### PR DESCRIPTION
**Pull request by molobala**
That will allow us to pass config object dynamically to driver when accessing them via  `disk` method of StorageManager

### CODE REVIEW

**Comment by molobala** [comment]
I have some troubleshoot to establish coherence betwen the two repositories, I think I will delete my repo and make a new fork

**Comment by RomainLanz** [comment]
Yes, it seems better to start from scratch and be careful about some files that shouldn't be commited (like `.idea/*`).

**Comment by molobala** [comment]
done

**Comment by molobala** [comment]
we can close that now

**Pull request closed without merging**
